# Generated by Django 2.2.3 on 2020-03-29 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ['-date_updated']},
        ),
    ]
