# Generated by Django 2.2.3 on 2020-03-29 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogsite', '0002_auto_20200329_0151'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='%d-%m-%Y/images'),
        ),
    ]
