# Generated by Django 2.2.3 on 2020-03-29 02:04

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogsite', '0003_subcategory_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='image',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='story',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='title',
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=500)),
                ('image', models.ImageField(blank=True, null=True, upload_to='%d-%m-%Y/images')),
                ('story', ckeditor.fields.RichTextField()),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogsite.Subcategory')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
