# Generated by Django 2.2.3 on 2020-03-29 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogsite', '0004_auto_20200329_0204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='blogsite.Subcategory'),
        ),
    ]
